### ISSUE TITLE
Disable scheduled action which builds Terraform for ppc64le

### ISSUE THREAD

**Issue by yussufsh** [ppc64le-development/terraform-ppc64le#1]

**Comment by yussufsh** [comment]
Can someone having write access to the repo do the required change?

**Comment by prb112** [comment]
Hey @snehagg24 or @rpsene do you still have access? could you assign access to Yussuf?

**Comment by snehagg24** [comment]
Sent invite to @yussufsh. Please confirm.

**Comment by yussufsh** [comment]
Thanks for the invite @snehagg24 👍

**Comment by yussufsh** [comment]
This issue is fixed.
Disabled the Actions and deleted the latest release.

**Comment by yussufsh** [comment]
> Sent invite to @yussufsh. Please confirm.

Would you be able to add me to the org itself? @snehagg24

**Comment by snehagg24** [comment]
sure @yussufsh sent an invite to add you to org

**Comment by prb112** [comment]
> Sent invite to @yussufsh. Please confirm.

Thank you

**Comment by yussufsh** [comment]
thanks again @snehagg24 👍
